version: '3'

services:
  db:
    image: mysql:8.0
    container_name: salovarov_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app_db
    volumes:
      - ../mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: salovarov_pma
    restart: always
    ports:
      - "3000:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin

  php:
    image: php:8.1-fpm
    container_name: salovarov_php
    restart: always
    volumes:
      - .:/var/www/html
    entrypoint:
      - sh
      - -c
      - "docker-php-ext-install mysqli && php-fpm"

  web:
    image: nginx:alpine
    container_name: salovarov_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro